# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080'] # Replace with the actual address of your API service

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:8081'] # Replace with the actual address of your Caddy service
